### ISSUE TITLE
upgrade to julia 0.6

### ISSUE THREAD

**Issue by alemelis** [INSIGNEO/openBF#1]
openBF currently runs on julia 0.3.x
when using julia 0.6, most of the type definitions are obsolete.

**Comment by alemelis** [comment]
Graphs.jl is not supported anymore starting from julia v.0.5.0

**Comment by alemelis** [comment]
[LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl) is an alternative library that can handle graphs

**Comment by alemelis** [comment]
LightGraphs does not keep track of the edge index

**Comment by alemelis** [comment]
Opened an [issue](https://github.com/JuliaGraphs/LightGraphs.jl/issues/698) on LightGraphs repo

**Comment by sbromberger** [comment]
Hi there. Let me know how I can help. One thing I noticed in a quick review of your code is that you're storing lists of edges created by the graph. This is generally not a great idea since it can take up a lot of memory. In LightGraphs, `edges(g)` provides an iterator to the graph edges (this is much more memory efficient). If you need the list despite all this, make sure you do a `collect(edges(g))` - but again, not a great idea, memory-wise.

**Comment by sbromberger** [comment]
Also, if you have specific files I should be looking at (that contain graph operations), please let me know and I can give you hits on how to convert to LG.

**Comment by alemelis** [comment]
Hey @sbromberger , thank you for pointing out this. I'll use the iterator from now on.

I replied on your repo, but if you prefer we can keep discussing it here. Thank you very much for your help :+1:
